#!/usr/bin/env python3
"""
Google Sheets Uploader for National Park Data

This script uploads the scraped national park data to a Google Sheet.

Required:
    - parks_data.json file (generated by national_park_scraper.py)
    - Google Sheets API credentials (service account JSON file)

Setup:
    1. Create a Google Cloud project
    2. Enable Google Sheets API
    3. Create a service account and download credentials JSON
    4. Share your Google Sheet with the service account email
    5. Set GOOGLE_SHEETS_CREDENTIALS environment variable to the path of your credentials file
"""

import os
import sys
import json
from typing import List, Dict
import gspread
from google.oauth2.service_account import Credentials


class GoogleSheetsUploader:
    """Uploader for National Park data to Google Sheets."""

    # Google Sheets API scope
    SCOPES = [
        'https://www.googleapis.com/auth/spreadsheets',
        'https://www.googleapis.com/auth/drive'
    ]

    def __init__(self, credentials_path: str):
        """
        Initialize the uploader.

        Args:
            credentials_path: Path to Google service account credentials JSON
        """
        self.credentials_path = credentials_path
        self.client = None

    def authenticate(self):
        """Authenticate with Google Sheets API."""
        try:
            creds = Credentials.from_service_account_file(
                self.credentials_path,
                scopes=self.SCOPES
            )
            self.client = gspread.authorize(creds)
            print("Successfully authenticated with Google Sheets API")
            return True
        except Exception as e:
            print(f"Authentication failed: {e}")
            return False

    def upload_data(self, spreadsheet_url: str, data: List[Dict], sheet_name: str = "National Parks"):
        """
        Upload park data to Google Sheet.

        Args:
            spreadsheet_url: URL of the Google Sheet
            data: List of park data dictionaries
            sheet_name: Name of the worksheet to create/update
        """
        try:
            # Open the spreadsheet
            print(f"Opening spreadsheet: {spreadsheet_url}")
            spreadsheet = self.client.open_by_url(spreadsheet_url)

            # Try to get the worksheet, create if it doesn't exist
            try:
                worksheet = spreadsheet.worksheet(sheet_name)
                print(f"Found existing worksheet: {sheet_name}")
                # Clear existing data
                worksheet.clear()
            except gspread.exceptions.WorksheetNotFound:
                worksheet = spreadsheet.add_worksheet(
                    title=sheet_name,
                    rows=len(data) + 1,
                    cols=10
                )
                print(f"Created new worksheet: {sheet_name}")

            # Prepare data for upload
            headers = [
                'Park Name',
                'State',
                'Established Year',
                'Size',
                'Description',
                'NPS URL',
                'Brochure Page URL',
                'Has Brochures',
                'Park Code'
            ]

            rows = [headers]

            for park in data:
                row = [
                    park.get('park_name', ''),
                    park.get('state', ''),
                    park.get('established_year', ''),
                    park.get('size', ''),
                    park.get('description', ''),
                    park.get('url', ''),
                    park.get('brochure_page_url', ''),
                    'Yes' if park.get('has_brochures', False) else 'No',
                    park.get('park_code', '')
                ]
                rows.append(row)

            # Upload all data at once
            print(f"Uploading {len(data)} parks to Google Sheet...")
            worksheet.update(rows, 'A1')

            # Format header row
            worksheet.format('A1:I1', {
                'textFormat': {'bold': True},
                'backgroundColor': {'red': 0.2, 'green': 0.6, 'blue': 0.2}
            })

            # Auto-resize columns
            for i in range(1, 10):
                worksheet.columns_auto_resize(i - 1, i)

            print(f"\n✓ Successfully uploaded {len(data)} parks to Google Sheet!")
            print(f"  View at: {spreadsheet_url}")

            return True

        except Exception as e:
            print(f"Error uploading to Google Sheet: {e}")
            return False


def load_parks_data(filename: str = 'parks_data.json') -> List[Dict]:
    """Load parks data from JSON file."""
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            data = json.load(f)
        print(f"Loaded {len(data)} parks from {filename}")
        return data
    except FileNotFoundError:
        print(f"ERROR: {filename} not found.")
        print("Please run national_park_scraper.py first to generate the data.")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON in {filename}: {e}")
        sys.exit(1)


def main():
    """Main execution function."""
    # Check for credentials
    creds_path = os.environ.get('GOOGLE_SHEETS_CREDENTIALS')
    if not creds_path:
        print("ERROR: GOOGLE_SHEETS_CREDENTIALS environment variable not set.")
        print("\nSetup instructions:")
        print("1. Create a Google Cloud project at: https://console.cloud.google.com")
        print("2. Enable the Google Sheets API")
        print("3. Create a service account and download credentials JSON")
        print("4. Share your Google Sheet with the service account email")
        print("5. Set the environment variable:")
        print("   export GOOGLE_SHEETS_CREDENTIALS='path/to/credentials.json'")
        sys.exit(1)

    if not os.path.exists(creds_path):
        print(f"ERROR: Credentials file not found at: {creds_path}")
        sys.exit(1)

    # Load parks data
    parks_data = load_parks_data()

    # Target Google Sheet URL
    spreadsheet_url = "https://docs.google.com/spreadsheets/d/1y9hv2TgbaoAsUqZVpd6TlnPGHKQ7r5JS6Zo-IjSatMw/edit?usp=sharing"

    # Create uploader and authenticate
    uploader = GoogleSheetsUploader(creds_path)

    if not uploader.authenticate():
        print("\nAuthentication failed. Please check your credentials.")
        sys.exit(1)

    # Upload data
    success = uploader.upload_data(spreadsheet_url, parks_data)

    if success:
        print("\n" + "=" * 80)
        print("SUCCESS! Data has been uploaded to Google Sheets")
        print("=" * 80)
    else:
        print("\nUpload failed.")
        sys.exit(1)


if __name__ == '__main__':
    main()
